### ISSUE TITLE
Array parameters are swallowed with `-D` in the parameter array value when using tkn task start 

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/cli#1103]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
Client version: 0.11.0
Pipeline version: v0.11.3
Triggers version: v0.4.0
  ```

- Operating System:

  ```
  macOS Catalina
  ```

# Expected Behavior

When I run tkn CLI command like 

```
tkn task start maven \
    --param=GOALS='-DskipTests' \
    --param=GOALS=clean \
    --param=GOALS=compile \
    --param=GOALS=jib:build \
    --param=GOALS='-Dimage=example.com/kameshs/tekton-git-jib-kn:v1' \
    --workspace=name=maven-settings,config=maven-settings  \
    --workspace=name=source,claimName=a-place-to-hold-stuff \
    --dry-run
```

I expect it to produce a YAML like 

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: maven-run-
  labels:
    tekton.dev/task: maven
spec:
  taskRef:
    name: maven
  params:
    - name: GOALS
      value:
        - -B
        - -DskipTests
        - clean
        - package
        - jib:build
        - -Dimage=example.com/kameshs/tekton-git-jib-kn:v1
  workspaces:
    - name: maven-settings
      configmap:
        name: maven-settings
    - name: source
      persistentVolumeClaim:
        claimName: a-place-to-hold-stuff
```

# Actual Behavior

But the YAML produced is 

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: maven-run-
  namespace: apipes
spec:
  params:
  - name: GOALS
    value:
    - -Dimage=example.com/kameshs/tekton-git-jib-kn:v1
  resources: {}
  serviceAccountName: ""
  taskRef:
    name: maven
  workspaces:
  - configMap:
      name: maven-settings
    name: maven-settings
  - name: source
    persistentVolumeClaim:
      claimName: a-place-to-hold-stuff
status:
  podName: ""

```

# Steps to Reproduce the Problem

1.  tkn task start maven \
    --param=GOALS='-DskipTests' \
    --param=GOALS=clean \
    --param=GOALS=compile \
    --param=GOALS='-Dimage=example.com/kameshs/tekton-git-jib-kn:v1' 
    --param=GOALS=jib:build 
    --workspace=name=maven-settings,config=maven-settings  \
    --workspace=name=source,claimName=a-place-to-hold-stuff \
    --dry-run

# Additional Info

Dont worry on the failure of the build but alteast the `GOALS` parameter should be able to run with all passed values.
