### ISSUE TITLE
Update release.sh to use tkn pipeline start 

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1174]
Currently, the [release script uses `kubectl`](https://github.com/tektoncd/cli/blob/ef620e0bbff28c68d6ae6decfe531d4763aa51b3/tekton/release.sh#L144) to create a PipelineRun for releasing `tkn`. We should have all the features in `tkn` to support using `tkn pipeline start`, and this will also help with dogfooding efforts for the project.

The command should be something like the following:
```
URL=$(git remote get-url ${PUSH_REMOTE}|sed 's,git@github.com:,https://github.com/,')
tkn pipeline start cli-release-pipeline -p revision=${RELEASE_VERSION} -p url=${URL} 
-w name=shared-workspace,volumeClaimTemplateFile=./volumeclaimtemplate.yaml
```

**volumeclaimtemplate.yaml:**

```yaml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
    storage: 500Mi
```
