### ISSUE TITLE
Prompts for Required Params Skipped if at Least One -p Value is Specified with task start Command

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#1180]
# Versions and Operating System

- Kubernetes version:

N/A

- Tekton Pipeline version:

```
v0.16.3
```

- Operating System:

```
Mac
```

# Expected Behavior

If a Task param is defined for a Task with no default value, that param is not specified by a user via `tkn task start`, and the user is not using the `--use-param-defaults` option, there should be a prompt while starting a Task to specify a value for the command:

```
? Value for param `seconds2` of type `string`? (Default is `1s`) (1s) 
```

# Actual Behavior

If at least one param is defined with a `tkn task start` command via `-p`, interactive prompts for params are skipped even if no values are provided for required params (i.e. those without default values). An interactive prompt should display in this case to ask for a param value. This results in a TaskRun being created that fails due to a `TaskRunValidationFailed` error.

This appears to be due to the `if` condition defined [here](https://github.com/tektoncd/cli/blob/3bdd4ae14975a69fe39d6d10b0f9fcb7229cbd8c/pkg/cmd/task/start.go#L529), which states that no params must be specified to begin prompting a user for params.

There should either be a validation error occurs that prevents the creation of a TaskRun, or there should be a prompt that occurs to make sure all required params have values for the TaskRun.

# Steps to Reproduce the Problem

1. Define a Task with two params (one with a default, one without a default):

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleep
spec:
  params:
  - name: seconds
    type: string
    default: 1s
  - name: seconds2
  steps:
    - name: sleep
      image: ubuntu
      command:
        - sleep
      args:
        - $(params.seconds)
    - name: echo2
      image: ubuntu
      command:
        - sleep
      args:
        - $(params.seconds2)
```

2. Start the Task with the default value param specified:

```
tkn t start sleep -p seconds=1s
```

3. TaskRun will start despite having no value specified for required `seconds2` param. Run `tkn tr ls` to find that the TaskRun has failed with a Status of `Failed(TaskRunValidationFailed)`.

# Additional Info

Noting that this also occurs with `tkn clusertask start`. Not sure if similar behavior would also occur with `tkn pipeline start`.
