### ISSUE TITLE
tkn keeps running after pipeline finishes when "retries" is used in pipeline

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#1459]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-30T00:00:00Z", GoVersion:"go1.16", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+9807387", GitCommit:"98073871f173baaa04dc2bafab50effd62c308a6", GitTreeState:"clean", BuildDate:"2021-08-06T14:06:43Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.20.0
  Pipeline version: v0.24.3
  Triggers version: v0.14.2
  ```

- Operating System:

  ```
  Fedora 34 (x86_64)
  ```

# Expected Behavior

`tkn pr logs -f --last` finishes (i.e. prompt is available again) when pipeline finishes.

# Actual Behavior

`tkn` keeps running after pipeline is done when `retries` is used in pipeline. Specifying `timeout` in either task or pipeline run has *NO* effect.

Works fine when `retries` is completely removed from pipeline or if set to 0.

# Steps to Reproduce the Problem

1. `oc apply -f timeout-pipeline2.yaml && oc create -f timeout-pipeline-run2.yaml && tkn pr logs -f --last`
2. wait ~30 seconds for pipeline to finish
3. tkn keeps running even though the pipeline finished
4. verify that pipeline finished `tkn pr ls`

# Additional Info

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: timeout-pipeline
spec:
  tasks:
  - name: mytask
    retries: 1
    taskSpec:
      steps:
      - name: hello
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          #!/usr/bin/env bash
          echo "Hello from task"
          sleep 10
          echo "Done"
```

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: timeout-pipeline-
spec:
  pipelineRef:
    name: timeout-pipeline
```
