### ISSUE TITLE
show steps in detailed format

### ISSUE THREAD

**Issue by developer-guy** [tektoncd/cli#1469]
### Feature request

In the describe command of `the task,` you'll see the list of steps with only their names. So, we(w/@dentrax @erkanzileli) propose adding more information about the steps once the user specifies a brand new flag called `--detailed.`

### Use case

The use case is as simple as specifying --detailed flag while issuing the command `tkn task describe <name_of_the_task>.`

### UI Example

The command will become to the following:

```shell
$ tkn task describe hello-task --detailed
```

For example, let's assume we have the following Task resource:

```YAML
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: say-something
spec:
  params:
    - name: say-what
      description: What should I say
      default: hello
      type: string
    - name: pause-duration
      description: How long to wait before saying something
      default: "0"
      type: string
  steps:
    - name: say-it
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'sleep $(params.pause-duration) && echo $(params.say-what)']
```

Once you've issued the command `tkn task describe say-something,` the will be similar to the following:

<details>

<summary> Output </summary>

```shell
Name:        say-something
Namespace:   default

Input Resources

 No input resources

Output Resources

 No output resources

Params

 NAME             TYPE     DESCRIPTION              DEFAULT VALUE
 say-what         string   What should I say        hello
 pause-duration   string   How long to wait be...   0

Results

 No results

Workspaces

 No workspaces

Steps

 say-it

Taskruns

 No taskruns

```

</details>

By this integration, the output would become this:

```shell
Steps

 say-it
   image:  registry.access.redhat.com/ubi8/ubi
   command: [ "/bin/bash" ]
    args:  ['-c', 'sleep $(params.pause-duration) && echo $(params.say-what)']
    ...
```
