### ISSUE TITLE
Support results of type array

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/cli#1576]
### Feature request

With release of Tekton Pipelines [v0.36.0](https://github.com/tektoncd/pipeline/releases/tag/v0.36.0), a new feature is added where a Task can produce results of type array. As of now this feature is present as an alpha feature and can be enabled by changing the value of `enable-api-fields` from `stable` to `alpha` in feature-flags configmap. With this the type of the result is changed from `string` to `ArrayOrString`. CLI should be able to handle that accordingly.

### Use case

A user should be able to view the results produced by Task/Pipelines based on their types once they switch the `enable-api-fields` value from `stable` to `alpha`. Also if somebody creates the Task with array results, in that case the existing CLI commands break with following error
```
$ tkn tr delete write-array-tr 
Error: failed to get TaskRun from namespace default
$ tkn tr ls                   
Error: failed to list TaskRuns from namespace default: unrecognized type: string
```

**Comment by vinamra28** [comment]
as discussed on [CLI WG call held on June 7, 2022](https://docs.google.com/document/d/1J1LkrmLtMdtdJqFcsyOKsJJc4lEm7YL-97D51PzpHrQ/edit#heading=h.qx5vuyc795o5), Bumping the pipelines dependency should work

**Comment by vinamra28** [comment]
it seems that bumping the dependency did it's job. If somebody want's to try this, probably can try the below example
```yaml
kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: write-array
  annotations:
    description: |
      A simple task that writes array
spec:
  results:
    - name: array-results
      type: array
      description: The array results
  steps:
    - name: write-array
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo -n "[\"hello\",\"world\"]" | tee $(results.array-results.path)
    - name: check-results-array
      image: ubuntu
      script: |
        #!/bin/bash
        VALUE=$(cat $(results.array-results.path))
        EXPECTED=[\"hello\",\"world\"]
        diff=$(diff <(printf "%s\n" "${VALUE[@]}") <(printf "%s\n" "${EXPECTED[@]}"))
        if [[ -z "$diff" ]]; then
            echo "TRUE"
        else
            echo "FALSE"
        fi
---
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: write-array-tr
spec:
  taskRef:
    name: write-array
    kind: Task
```
