### ISSUE TITLE
Segfault from `tkn taskrun list` when incomplete run in list

### ISSUE THREAD

**Issue by ahpook** [tektoncd/cli#168]
I was using tkn to try to debug a problem starting the sample 'helloworld' task run, and got a segfault in the `printFormatted` function, due to an unhandled nil in the task output.

# Actual Behavior

See https://gist.github.com/ahpook/9e20ea7395e099e4d21547024bfd40b7 for the error output.

# Expected Behavior

It should not segfault.

# Steps to Reproduce the Problem

1. Follow the hello world tutorial up to the point where you've created the taskrun
2. Prevent the run from completing successfully - I'm not sure how it got into this state, that's the problem I was originally trying ot troubleshoot!  See attached `kubectl describe` output 
3. run `tkn taskrun list` , observe segfault

# Additional Info

I suspect it's the `formatted.Condition(tr.Status.Conditions[0]),` argument at [cli/list.go#L138](https://github.com/tektoncd/cli/blob/master/pkg/cmd/taskrun/list.go#L138), since when i set a breakpoint and looked into that part of the struct it was empty, and the [receiving method](https://github.com/tektoncd/cli/blob/master/pkg/formatted/k8s.go#L9) doesn't check for type before calling `c.Status` on it - but I got bogged down trying to figure out how best to fix it.

The failed run looks like this:

```yaml
Name:         echo-hello-world-task-run
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"tekton.dev/v1alpha1","kind":"TaskRun","metadata":{"annotations":{},"name":"echo-hello-world-task-run","namespace":"default"},"spec":{"ta...
API Version:  tekton.dev/v1alpha1
Kind:         TaskRun
Metadata:
  Creation Timestamp:  2019-06-26T22:54:59Z
  Generation:          1
  Resource Version:    16591574
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/default/taskruns/echo-hello-world-task-run
  UID:                 6c8b4d24-9865-11e9-b2a7-fa163e77a488
Spec:
  Inputs:
  Outputs:
  Task Ref:
    Kind:  Task
    Name:  echo-hello-world
Events:    <none>
```
