### ISSUE TITLE
Bundle push not working when authentication is passed through args

### ISSUE THREAD

**Issue by lstocchi** [tektoncd/cli#1718]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.24.0
Pipeline version: v0.37.0
Triggers version: v0.20.2
```

- Operating System:

```
linux fedora
```

# Expected Behavior

When trying to push a bundle to my quay.io repo using the username and password flags i expect it to works

# Actual Behavior

I see  this error 
```
Error: could not push image to registry as "quay.io/lstocchi/sumtest:latest": provide an option for either authn.Authenticator or authn.Keychain, not both
```

# Steps to Reproduce the Problem

1. Have a yaml file `mybundle.yaml` with a pipeline in it. I used this
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sum-pipeline
  namespace: default
spec:
  params:
  - description: first operand
    name: first
    type: string
  - description: second operand
    name: second
    type: string
  tasks:
  - name: add
    params:
    - name: a
      value: $(params.first)
    - name: b
      value: $(params.second)
    taskRef:
      kind: Task
      name: sum-params
```
2. Execute the command without username and psw flags and receive a 401 error (expected - I don't have any local auth config file).
```
tkn bundle push quay.io/lstocchi/sumtest:latest -f mybundle.yaml 
Creating Tekton Bundle:
	- Added Pipeline: sum-pipeline to image
Error: could not push image to registry as &quot;quay.io/lstocchi/sumtest:latest&quot;: HEAD https://quay.io/v2/lstocchi/sumtest/blobs/sha256:f21dda0ceb6712b2914203ddc401050aea15a67905f6300574e26f7483600224: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
```
3. Execute the command with the username and psw flags
```
tkn bundle push quay.io/lstocchi/sumtest:latest -f mybundle.yaml --remote-username=lstocchi --remote-password=*****
Creating Tekton Bundle:
	- Added Pipeline: sum-pipeline to image
Error: could not push image to registry as "quay.io/lstocchi/sumtest:latest": provide an option for either authn.Authenticator or authn.Keychain, not both
```

# Additional Info
We were asked to add support for tekton bundle in the IDE Tekton plugins. I cannot expect all users to have the local docker.json/podmain auth.json rightly configured and need to provide a way to make it works. Any other hack/idea is welcome.
