### ISSUE TITLE
Validate pipelines on the cluster

### ISSUE THREAD

**Issue by adelmoradian** [tektoncd/cli#1791]
### Feature request

`tkn` should do pipeline validation based on tasks/clusterTasks that are available in the cluster. 

### Use case

Take the following tasks and pipeline for example… I can do `kubectl apply -f` however my pipeline has the following issues:
- task-a and task-b  both need params that are not specified in the pipeline spec (same thing can happen with workspaces)…
- task-b  is a Task but in pipeline, the kind is ClusterTask
- task-c  is used in the pipeline but does not exist in my cluster

I would like to be able to run a command like `tkn doctor` or `tkn pipeline validate` which will highlight such issues. I can also use this my catalog CI. Additionally, would be nice to have the ability to provide a pipeline file with `-f` flag to validate it against tasks in my cluster!

Initially I was thinking it should throw warning if we have extra unused params in `spec.params` however I think that should be the job of a linter.

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  params:
    - name: param-a
    - name: param-b
    - name: param-c
  tasks:
    - name: task-a
      taskRef:
        name: task-a
      params:
        - name: param-a
          value: $(params.param-a)
    - name: task-b
      taskRef:
        kind: ClusterTask
        name: task-b
      params:
        - name: param-b
          value: $(params.param-b)
    - name: task-c
      taskRef:
        name: task-c
      params:
        - name: param-c
          value: $(params.param-c)

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-a
spec:
  params:
    - name: param-a
    - name: param-a-missed
  steps:
    - image: ubuntu
      script: echo 'hello there'

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-b
spec:
  params:
    - name: param-b
    - name: param-b-missed
  steps:
    - image: ubuntu
      script: echo 'hello there'
```

### UI Example

```bash
> tkn doctor
test-pipeline in default namespace has the following issues:
- task-a is missing required params: param-a-missed
- task-b is missing required params: param-b-missed
- the following tasks/clusterTasks are used in the pipeline but do not exist in the cluster: clusterTasks [task-b] - tasks [task-c]
test-pipeline-2 in test-ns namespace has the following issues:
- task-d is missing required workspaces: ws-d

> echo $?
1

> tkn doctor -f pipeline.yaml
test-pipeline-3 is valid!

> echo $?
0
```
