### ISSUE TITLE
Can't read v1beta1 pipelineruns logs

### ISSUE THREAD

**Issue by deepio** [tektoncd/cli#1865]
# Versions and Operating System

- Kubernetes version: 1.25.4

  **Output of `kubectl version`:**

```bash
#kubectl version --output=yaml
clientVersion:
  buildDate: "2022-05-24T12:17:11Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-12-16T19:44:08Z"
  compiler: gc
  gitCommit: b969368e201e1f09440892d03007c62e791091f8
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```v0.43.2```

- Operating System:

```macos 12.5.1```

# Expected Behavior

Logs

# Actual Behavior

```
W0125 12:45:25.473679   35773 reflector.go:347] github.com/tektoncd/pipeline/pkg/client/informers/externalversions/factory.go:117: watch of *v1.PipelineRun ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"PipelineRun\" is registered for version \"tekton.dev/v1\" in scheme \"github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme/register.go:32\"") has prevented the request from succeeding
```

# Steps to Reproduce the Problem

1. Don't use `tekton.dev/v1` because you can't specify serviceAccountName https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-pipelinerun
```bash
# When you do use v1, you get this.
admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccountName"
```
2. Apply a pipelinerun: `kubectl apply -f test.yaml`
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "testing-stuff"
  namespace: <snip>
  labels:
    app.kubernetes.io/name: python
    app.kubernetes.io/component: pipelinerun
    app.kubernetes.io/part-of: <snip>
    app.kubernetes.io/managed-by: <snip>
spec:
  serviceAccountName: <snip>
  pipelineRef:
    name: run-python-tests
  timeouts:
    pipeline: "3h0m0s"
  params:
    <snip>

  workspaces:
    - name: codebase
      volumeClaimTemplate:
        metadata:
          name: testing-stuff"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
```
3. If you ask for the logs using something like k9s or lens, you can see them and the build is running.
4. `kubectl logs --selector=tekton.dev/pipelineRun=testing-stuff -n harbormaster --all-containers` doesn't give logs for the tasks, only the pipelinerun? Must use `selector=tekton.dev/taskRun` to get the task logs?

# Additional Info
This may be a problem for both pipelines and the cli
