### ISSUE TITLE
Listing Pipelines breaks when using both `--all-namespaces` and `--output yaml`

### ISSUE THREAD

**Issue by AverageMarcus** [tektoncd/cli#1888]
# Versions and Operating System

- Kubernetes version: 

  **Output of `kubectl version`:**

  ```
  Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.29.1
  Pipeline version: v0.44.0
  Triggers version: v0.22.1
  Dashboard version: v0.32.0
  ```

- Operating System:

  ```
  MacOS
  ```

# Expected Behavior

`tkn pipeline list --all-namespaces --output yaml` should display all Pipelines.

Listing without changing the output still works:
```
┗ ✨ tkn pipeline list  --all-namespaces             
NAMESPACE   NAME                 AGE         LAST RUN   STARTED   DURATION   STATUS
test-1      build-docker-image   1 day ago   ---        ---       ---        ---
```

As does output with yaml while specifying a namespace:
```
┗ ✨ tkn pipeline list --namespace test-1 --output yaml
apiVersion: tekton.dev/v1
items:
- apiVersion: tekton.dev/v1
  kind: Pipeline
  metadata:
    name: build-docker-image
    namespace: test-1
--- etc ---
```

# Actual Behavior

```
┗ ✨ tkn pipeline list --all-namespaces --output yaml
apiVersion: tekton.dev/v1
items: []
kind: PipelineList
metadata:
  continue: ""
  resourceVersion: "7998563"
```

# Steps to Reproduce the Problem

1. Create Pipeline resources in multiple namespaces
2. Run `tkn pipeline list --all-namespaces --output yaml`

# Additional Info
