### ISSUE TITLE
Logs for a Matrix PipelineTask does not include logs for all TaskRuns Fanned Out

### ISSUE THREAD

**Issue by EmmaMunley** [tektoncd/cli#2089]
# Versions and Operating System

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.3
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
Client version: 0.31.1
Pipeline version: devel
  ```

- Operating System:

  ```
Mac OS 13.5
  ```

# Expected Behavior

When fanning out a Matrixed PipelineTask I expect to see the logs for all of the TaskRuns created - for example, below we are echoing platform and browser for 9 combinations that are fanned out into 9 TaskRuns from the Matrixed PipelineRun - I expect when I get the pr logs, it would show the logs for all 9 TaskRuns:

```
[platforms-and-browsers : echo] linux and chrome
[platforms-and-browsers : echo] mac and chrome
[platforms-and-browsers : echo] windows and chrome
[platforms-and-browsers : echo] linux and safari
[platforms-and-browsers : echo] mac and safari
[platforms-and-browsers : echo] windows and safari
[platforms-and-browsers : echo] linux and firefox
[platforms-and-browsers : echo] mac and firefox
[platforms-and-browsers : echo] windows and firefox
```

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: platform-browsers
  annotations:
    description: |
      A task that does something cool with platforms and browsers
spec:
  params:
    - name: platform
    - name: browser
  steps:
    - name: echo
      image: alpine
      script: |
        echo "$(params.platform) and $(params.browser)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: matrixed-pr-
spec:
  serviceAccountName: "default"
  pipelineSpec:
    tasks:
      - name: platforms-and-browsers
        matrix:
          params:
            - name: platform
              value:
                - linux
                - mac
                - windows
            - name: browser
              value:
                - chrome
                - safari
                - firefox
        taskRef:
          name: platform-browsers
```

# Actual Behavior
 tkn pr logs output

```
[platforms-and-browsers : echo] linux and safari
```
# Steps to Reproduce the Problem

1. Run the example yaml
2. View the logs

# Additional Info
