### ISSUE TITLE
tkn throw errors for array type params

### ISSUE THREAD

**Issue by garethr** [tektoncd/cli#220]
# Expected Behavior

When running `tkn task list` and `tkn taskrun logs`, after having defined a task with a param of type: `array`, tkn should not error.

# Actual Behavior

`tkn task list` throws an error when and does not list any tasks.

# Steps to Reproduce the Problem

Consider the following definition

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: minimal
spec:
  inputs:
    params:
    - name: args
      type: array
      default: []

  steps:
  - name: command
    image: docker/whalesay:latest
    command:
      - cowsay
      - $(inputs.params.args)
```

Applying this works as expected.

```console
$ kubectl apply -f minimal.yaml
task.tekton.dev/minimal create
```

The task exists:

```console
$ kubectl get task
NAME      AGE
minimal   6s

But `tkn task list` errors.

$ tkn task list
No tasks found
Error: v1alpha1.TaskList.Items: []v1alpha1.Task: v1alpha1.Task.Spec: v1alpha1.TaskSpec.Inputs: v1alpha1.Inputs.Params: []v1alpha1.ParamSpec: v1alpha1.ParamSpec.Default: ReadString: expects " or n, but found [, error found in #10 byte of ...|default":[],"name":"|..., bigger context ...|c110002"},"spec":{"inputs":{"params":[{"default":[],"name":"args","type":"array"}]},"steps":[{"comma|...
Usage:
...
```

Apply the following taskrun spec works as expected:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: minimal-example
spec:
  taskRef:
    name: minimal
```

And `tkn` can access the logs.

```
$ tkn taskrun logs minimal-example -a -f
[credential-initializer-82z7h] {"level":"warn","ts":1566139922.5577986,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
[credential-initializer-82z7h] {"level":"info","ts":1566139922.5590403,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}


[command]  _
[command] <   >
[command]  -
[command]     \
[command]      \
[command]       \
[command]                     ##        .
[command]               ## ## ##       ==
[command]            ## ## ## ##      ===
[command]        /""""""""""""""""___/ ===
[command]   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
[command]        \______ o          __/
[command]         \    \        __/
[command]           \____\______/
```

We can also create a taskspec that uses the array arguments

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: minimal-example-2
spec:
  taskRef:
    name: minimal
  inputs:
    params:
    - name: args
      value:
      - hello
      - tekton
```

Applying this succeeds, but `tkn` fails to return the results.

```console
$ tkn taskrun logs minimal-example-2 -a -f
Error: Unable to get Taskrun : v1alpha1.TaskRun.Spec: v1alpha1.TaskRunSpec.Inputs: v1alpha1.TaskRunInputs.Params: []v1alpha1.Param: v1alpha1.Param.Value: ReadString: expects " or n, but found [, error found in #10 byte of ...|,"value":["hello","t|..., bigger context ...|pec":{"inputs":{"params":[{"name":"args","value":["hello","tekton"]}]},"outputs":{},"podTemplate":{}|...
```

But Tekton did run the task, we can access the logs directly from the pod. Note the `hello tekton` message.

```console
$ kubectl logs minimal-example-2-pod-e425b2
 ______________
< hello tekton >
 --------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```
