### ISSUE TITLE
Describe task does not work for inline task spec

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#380]
# Expected Behavior

```
tkn taskrun describe taskrun_name
```

This should show the description of taskrun

# Actual Behavior

```
tkn taskrun describe task-59p7t          
Failed to execute templateError: template: Describe taskrun:3:21: executing "Describe taskrun" at <.TaskRun.Spec.TaskRef.Name>: nil pointer evaluating *v1alpha1.TaskRef.Name
```

# Steps to Reproduce the Problem

1. Create a taskrun with inline spec like

```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: task-
spec:
  taskSpec:
    steps:
      - name: test
        image: ubuntu
        command: ["/bin/bash"]
        args:
          - -c
          - |
            set -e
            set -x
            echo hello world
```
2. Get the taskrun name
```
tkn taskrun list           
NAME         STARTED         DURATION     STATUS      
task-59p7t   2 minutes ago   13 seconds   Succeeded
```
3. Hit describe command
```
tkn taskrun describe task-59p7t          
Failed to execute templateError: template: Describe taskrun:3:21: executing "Describe taskrun" at <.TaskRun.Spec.TaskRef.Name>: nil pointer evaluating *v1alpha1.TaskRef.Name
```

# Additional Info

CLI version 0.4.0
