### ISSUE TITLE
tkn pipeline start or tkn task start failure on array params

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/cli#468]
# Expected Behavior

`It should work`

# Actual Behavior

`If you create a pipeline or task with array param, and provide single value to params it fails`

# Steps to Reproduce the Problem

1. Create pipeline or task with array param
2. Execute `tkn pipeline start -p paramName=boom`
3. It fails

# Additional Info

/kind bug

**Comment by waveywaves** [comment]
With

**Comment by waveywaves** [comment]
With the following pipeline
```
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipeline-cluster-task-4
spec:
  tasks:
  - name: cluster-task-pipeline-4
    taskRef:
      name: cluster-task-pipeline-4
      kind: ClusterTask

  params:
    - name: a
      type: array
```
and the following command 

`$ tkn pipeline start sample-pipeline-cluster-task-4 -p a=qwe`

we get the following output with error

```
Pipelinerun started: sample-pipeline-cluster-task-4-run-8rgmb
Showing logs...
PipelineRun tekton-pipelines/sample-pipeline-cluster-task-4-run-8rgmb parameters have mismatching types with Pipeline tekton-pipelines/sample-pipeline-cluster-task-4's parameters: parameters have inconsistent types : [a]
```

is this the same error you are facing @piyush-garg ?
