### ISSUE TITLE
nil pointer from pipelinerun describe 

### ISSUE THREAD

**Issue by Conky5** [tektoncd/cli#584]
# Version and Operating System

**tkn Version:** 0.6.0

**Operating System:** alpine linux

# Expected Behavior

`tkn pipelinerun describe <name>` should show not `panic`.

# Actual Behavior

This error message is thrown:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10de379]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).Before(...)
        /workspace/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004074956-01f8b7d1121a/pkg/apis/meta/v1/time.go:75
github.com/tektoncd/cli/pkg/cmd/pipelinerun.taskrunList.Less(...)
        /workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/describe.go:222
sort.insertionSort(0x15d5e80, 0xc000569360, 0x0, 0x4)
        /usr/local/go/src/sort/sort.go:27 +0xc4
sort.quickSort(0x15d5e80, 0xc000569360, 0x0, 0x4, 0x6)
        /usr/local/go/src/sort/sort.go:209 +0x201
sort.Sort(0x15d5e80, 0xc000569360)
        /usr/local/go/src/sort/sort.go:218 +0x79
github.com/tektoncd/cli/pkg/cmd/pipelinerun.printPipelineRunDescription(0xc00040bd40, 0x7ffd93d66577, 0xe, 0x15ebf80, 0xc000395600, 0x8, 0x7ffd93d66500)
        /workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/describe.go:146 +0x91a
github.com/tektoncd/cli/pkg/cmd/pipelinerun.describeCommand.func1(0xc0003d1080, 0xc0003fca50, 0x1, 0x3, 0x0, 0x0)
        /workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/describe.go:121 +0x18a
github.com/spf13/cobra.(*Command).execute(0xc0003d1080, 0xc0003f06c0, 0x3, 0x4, 0xc0003d1080, 0xc0003f06c0)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:832 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000391340, 0xc000395600, 0xc000391340, 0xc00009a058)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:920 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:870
main.main()
        /workspace/src/github.com/tektoncd/cli/cmd/tkn/main.go:31 +0x4b
```

# Steps to Reproduce the Problem

1. Start a pipeline with multiple tasks in it
2. Immediately run a describe on it

**Comment by danielhelfand** [comment]
@Conky5 Thanks for reporting/sorry for the issue. Could you possibly share your pipeline definition or something similar to it?

**Comment by danielhelfand** [comment]
I think the issue is actually here:

https://github.com/tektoncd/cli/blob/32662c8afa4e5376f8be4ebd3afa8e2724c4f50f/pkg/cmd/pipelinerun/describe.go#L222

There is no nil check like we traditionally do for sorting taskruns:

https://github.com/tektoncd/cli/blob/32662c8afa4e5376f8be4ebd3afa8e2724c4f50f/pkg/helper/taskrun/sort/sort_taskruns.go#L25

**Comment by Conky5** [comment]
Hi @danielhelfand, here is the pipeline and task definition I am seeing this with:

```
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test
spec:
  inputs:
    params:
      - name: exitCode
        description: The exit code the task should exit with.
        default: "0"
  steps:
    - name: test
      image: busybox
      args:
        - "-c"
        - |
          echo "Hello, world!"
          exit $(inputs.params.exitCode)
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: test
spec:
  params:
    - name: exitCode
      description: Exit code the task should exit with.
      default: "0"
  tasks:
    - name: test-1
      taskRef:
        name: test
      params:
      - name: exitCode
        value: "$(params.exitCode)"
    - name: test-2
      taskRef:
        name: test
      params:
      - name: exitCode
        value: "$(params.exitCode)"
    - name: test-3
      taskRef:
        name: test
      params:
      - name: exitCode
        value: "$(params.exitCode)"
    - name: test-4
      taskRef:
        name: test
      params:
      - name: exitCode
        value: "$(params.exitCode)"
```

The pipeline is being started with:
```
tkn pipeline start --showlog=false "test" --param exitCode=0
```
