### ISSUE TITLE
Missing OIDC support with Azure Active Directory

### ISSUE THREAD

**Issue by tomhau01** [tektoncd/cli#627]
# Version and Operating System

**tkn Version:**
0.6.0

**Operating System:** 
macOS

# Expected Behavior
1) Have a k8s cluster where OIDC is enabled and using Azure AD: https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/azure
2) use a kubeconfig with Azure AD enabled:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: < cert>
    server: https://<my k8s apiserver>:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: oidc
  name: my-cluster-system
current-context: my-cluster-system
kind: Config
preferences: {}
users:
- name: oidc
  user:
    auth-provider:
      config:
        access-token: <ey...>
        apiserver-id: <my apiserver id
        client-id: <my client id>
        environment: AzurePublicCloud
        expires-in: "3600"
        expires-on: "1561668931"
        refresh-token: <token>
        tenant-id: <my tenant id>
      name: azure
```
3) issue some tkn command, like 

> tkn pr list

and it works

# Actual Behavior
```
$ tkn pr list
Error: No Auth Provider found for name "azure"
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
