### ISSUE TITLE
There is no flag for specifying workspace for pipeline run

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#735]
# Version and Operating System

**tkn Version:**

0.7.1

**Operating System:** 

All

# Expected Behavior

I can start a pipeline with a workspace by specifying all data it needs in flags

# Actual Behavior

There is no flag for specifying PVCs for workspaces on command line, one needs to create a yaml file and then create a pipeline run from this yaml.

# Steps to Reproduce the Problem

1. clone https://github.com/siamaksade/tekton-pipelines-maven-demo/tree/80cbe3944aafd62b2fba70b53d1ca44e8a224d06
2. `kubectl create -f pvc.yaml`
3. `kubectl create -f maven-task.yaml`
4. `kubectl create -f maven-pipeline.yaml`
5. 
```
cat <<EOF | kubectl create -f -
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/spring-projects/spring-petclinic
EOF
``` 
6. `tkn p start -r app-git=app-git  maven-build --showlog`

result:
```
Pipelinerun started: maven-build-run-7r687
Showing logs...
PipelineRun maventest1/maven-build-run-7r687 doesn't bind Pipeline maventest1/maven-build's Workspaces correctly: pipeline expects workspace with name "local-maven-repo" be provided by pipelinerun
```
