### ISSUE TITLE
Add Task param values set in pipeline describe command

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#765]
A little bit related #764, it would be nice to enhance the `tkn pipeline describe` subcommand by adding the parameter values passed for Tasks used in the pipeline.

For example, for the following `Pipeline` spec…

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cli-release-pipeline
spec:
  params:
  - name: package
    description: package to release
    default: github.com/tektoncd/cli
  # FIXME(vdemeester): this is not yet used and need to be fixed upstream
  - name: github-token-secret
    description: name of the secret holding the github-token
    default: bot-token-github
  resources:
  - name: source-repo
    type: git
  tasks:
    - name: lint
      taskRef:
        name: golangci-lint
      params:
        - name: package
          value: $(params.package)
        - name: flags
          value: -v
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: unit-tests
      runAfter: [lint]
      taskRef:
        name: golang-test
      params:
        - name: package
          value: $(params.package)
        - name: version
          value: 1.13.8
        - name: flags
          value: -v -mod=vendor
      resources:
        inputs:
          - name: source
            resource: source-repo
```

… I would like to see that we used the different parameters values for each task (here `golangci-lint` and `golang-test`. We may want to add different level of output for the `describe` commands (like `short`, `wide`, …).

```
🗒  Tasks

 NAME           TASKREF         RUNAFTER    PARAMS
 ∙ lint         golangci-lint                                package:$(params.package), flags:-v
 ∙ unit-tests   golang-test     lint                    package:$(param.package), version:1.13.8, value:-v -mod=vendor
```

/kind feature
