### ISSUE TITLE
Cannot override paths when starting a task

### ISSUE THREAD

**Issue by lstocchi** [tektoncd/cli#807]
Currently when starting a task one can set input/output resources by using -i and -o flags. It would be nice if one could also override the paths of a resource like it's possible when defining the configuration file

```
outputs:
      - name: workspace
        paths:
          - /custom/workspace/
        resourceRef:
          name: java-git-resource
```
