### ISSUE TITLE
Inputs/Outputs/Params No Longer Being Displayed in Describe Commands

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#817]
I am assuming the switch to the spec in pipeline where inputs/outputs/params are under resources/spec has broken describe commands, which still reference these values using the old structure:

https://github.com/tektoncd/cli/blob/95ed643507bcda2235ba9c598871beb2fa04607d/pkg/cmd/task/describe.go#L52

Perhaps an update to `spec.resources.inputs`, `spec.resources.outputs`, and `spec.params` is the fix.

**Version:** 

```
tkn version
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
```

# Expected Behavior

Input/Output/Params are displayed when describing resources.

# Actual Behavior

```
$ tkn t desc build-docker-image-from-git-source

tkn t desc build-docker-image-from-git-source
Name:        build-docker-image-from-git-source
Namespace:   default

📨 Input Resources

 No input resources

📡 Output Resources

 No output resources

⚓ Params

 No params

🦶 Steps

 ∙ build-and-push

🗂  Taskruns

NAME                                           STARTED          DURATION    STATUS
build-docker-image-from-git-source-run-bzgl6   50 minutes ago   4 minutes   Succeeded
```

# Additional Info

YAML for Task:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/docker-source/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: /workspace/docker-source
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url)
        - --context=$(params.pathToContext)
```
