### ISSUE TITLE
How to start a pipeline with default params in a non-interactive shell

### ISSUE THREAD

**Issue by ckadner** [tektoncd/cli#820]
# Version and Operating System

**`tkn` version:**
```
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
```

**Operating System:** MacOS 10.15 (Catalina)

# Expected Behavior

I was expecting there to be a flag that allows to run pipelines/tasks with parameter default values (if so defined) without prompting for user input, i.e.:

`tkn pipeline start <pipeline-name> --params-use-defaults`

This would be usefull when running pipelines from within a shell script

# Actual Behavior

When starting a pipeline, user get's prompted to confirm or override the default values for each pipeline parameter.

# Additional Info

```YAML
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gcs-download
spec:
  inputs:
    params:
    - name: url
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url)
    - /tmp/results.txt
    command:
    - sh
    - -c
    image: google/cloud-sdk:216.0.0
    name: gcs-download
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo
spec:
  inputs:
    params:
    - name: path
  steps:
  - args:
    - echo "$0"
    - $(inputs.params.path)
    command:
    - sh
    - -c
    image: library/bash:4.4.23
    name: echo
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline with two sequential
      steps.", "inputs": [{"default": "gs://ml-pipeline-playground/shakespeare1.txt",
      "name": "url", "optional": true}, {"default": "/tmp/results.txt", "name": "path",
      "optional": true}], "name": "Sequential pipeline"}'
  name: sequential-pipeline
spec:
  params:
  - default: gs://ml-pipeline-playground/shakespeare1.txt
    name: url
  - default: /tmp/results.txt
    name: path
  tasks:
  - name: gcs-download
    params:
    - name: url
      value: $(params.url)
    taskRef:
      name: gcs-download
  - name: echo
    params:
    - name: path
      value: $(params.path)
    runAfter:
    - gcs-download
    taskRef:
      name: echo
```
