### ISSUE TITLE
`tkn describe pipelinerun` crashes with a Condition

### ISSUE THREAD

**Issue by rvandegrift** [tektoncd/cli#882]
I have been seeing `tkn` crash after adding a `Condition` to a `Pipeline`.  It's not 100% of the time:
- it seems worse right after creating the `PipelineRun`, and then may eventually settle out.
- it seems like a failed `Task` can make it never recover.

The backtraces match in terms of files & lines indicated.  The one below is representative.

# Version and Operating System

**tkn Version:** 0.8.0

**Operating System:** Debian buster

# Expected Behavior
not crashing :)

# Actual Behavior

```
$ tkn pipelinerun describe hello-hello --context tekton
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1130806]

goroutine 1 [running]:
github.com/tektoncd/cli/pkg/helper/pipelinerun/description.taskrunList.Less(0xc00011a540, 0x3, 0x4, 0x2, 0x1, 0xc00002da00)
        /workspace/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/description/description.go:85 +0x66
sort.insertionSort(0x175a960, 0xc0004133c0, 0x0, 0x3)
        /usr/local/go/src/sort/sort.go:27 +0xc4
sort.quickSort(0x175a960, 0xc0004133c0, 0x0, 0x3, 0x4)
        /usr/local/go/src/sort/sort.go:209 +0x201
sort.Sort(0x175a960, 0xc0004133c0)
        /usr/local/go/src/sort/sort.go:218 +0x79
github.com/tektoncd/cli/pkg/helper/pipelinerun/description.PrintPipelineRunDescription(0xc00002dd40, 0x7fff033ea800, 0xb, 0x1772200, 0xc0002f6040, 0x0, 0x0)
        /workspace/src/github.com/tektoncd/cli/pkg/helper/pipelinerun/description/description.go:126 +0x883
github.com/tektoncd/cli/pkg/cmd/pipelinerun.describeCommand.func1(0xc000314dc0, 0xc00032ae40, 0x1, 0x3, 0x0, 0x0)
        /workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/describe.go:73 +0x20b
github.com/spf13/cobra.(*Command).execute(0xc000314dc0, 0xc00032adb0, 0x3, 0x3, 0xc000314dc0, 0xc00032adb0)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20200107083527-379e7a80af0c/command.go:834 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ee2c0, 0xc0002f6040, 0xc0002ee2c0, 0xc0000a0058)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20200107083527-379e7a80af0c/command.go:922 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20200107083527-379e7a80af0c/command.go:872
main.main()
        /workspace/src/github.com/tektoncd/cli/cmd/tkn/main.go:29 +0x4b
```

# Steps to Reproduce the Problem

1. `kubectl apply` the config below (sorry for the "minimal" config - this produces the most robust failures.)
1. `tkn pipelinerun describe hello-hello`

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  params:
    - name: greeting
      type: string
  steps:
    - name: echo
      image: debian:buster-slim
      command:
        - echo
      args:
        - "Hello World: $(params.greeting)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pause
spec:
  params:
    - name: duration
      type: string
  steps:
    - name: echo
      image: debian:buster-slim
      command:
        - echo
      args:
        - "Sleeping for $(params.duration)"
    - name: sleep
      image: debian:buster-slim
      command:
        - sleep "$(params.duration)"   # mistake included on purpose

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-hello
spec:
  params:
    - name: first-hello
      type: string
      default: wooo
    - name: second-hello
      type: string
      default: yeah
    - name: third-hello
      type: string
      default: heyy
    - name: do-extra-hello
      type: string
      default: "false"
  tasks:
    - name: first-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.first-hello)"

    - name: pause-after-first
      taskRef:
        name: pause
      params:
        - name: duration
          value: "60"

    - name: second-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.second-hello)"
      runAfter:
        - first-hello

    - name: third-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.third-hello)"
      runAfter:
        - first-hello
      conditions:
        - conditionRef: do-extra-hello
          params:
            - name: do-extra-hello
              value: "$(params.do-extra-hello)"

---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: do-extra-hello
spec:
  params:
    - name: do-extra-hello
  check:
    image: debian:buster-slim
    script: '[ "$(params.do-extra-hello)" = "true" ]'

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-hello
spec:
  pipelineRef:
    name: hello-hello
  params:
    - name: first-hello
      value: asdf
    - name: second-hello
      value: zxcv
    - name: do-extra-hello
      value: "true"

```

**Comment by danielhelfand** [comment]
@rvandegrift Are you sure you are using `v0.8.0`? I notice the error is coming from a package the CLI doesn't have in `v0.8.0` called `helper`, which was removed before `v0.8.0`.

I want to say the error was resolved in this pr: https://github.com/tektoncd/cli/pull/586

**Comment by danielhelfand** [comment]
Looking a little deeper, it seems as if the TaskRun status is being returned as nil and causing the panic  here:

https://github.com/tektoncd/cli/blob/6eae6df140e49e4bee01e65b4967bbf269d10c34/pkg/pipelinerun/description/description.go#L111

Not exactly sure what is leading to this, but adding a nil check on status results in the following:

```
Name:           hello-hello
Namespace:      default
Pipeline Ref:   hello-hello
Timeout:        1h0m0s
Labels:
 tekton.dev/pipeline=hello-hello

🌡️  Status

STARTED       DURATION     STATUS
3 hours ago   27 seconds   Failed

💌 Message

TaskRun hello-hello-pause-after-first-22jd9 has failed ("step-sleep" exited with code 1 (image: "docker-pullable://debian@sha256:76c15066d7db315b42dc247b6d439779d2c6466f7dc2a47c2728220e288fc680"); for logs run: kubectl -n default logs hello-hello-pause-after-first-22jd9-pod-4m9th -c step-sleep)

📦 Resources

 No resources

⚓ Params

 NAME               VALUE
 ∙ first-hello      asdf
 ∙ second-hello     zxcv
 ∙ do-extra-hello   true

🗂  Taskruns

failed to execute template: Error: template: Describe Pipelinerun:66:98: executing "Describe Pipelinerun" at <$taskrun.Status.StartTime>: nil pointer evaluating *v1beta1.TaskRunStatus.StartTime
```

There's also the issue of doing a nil check in the template used by the command here:

https://github.com/tektoncd/cli/blob/6eae6df140e49e4bee01e65b4967bbf269d10c34/pkg/pipelinerun/description/description.go#L97

**Comment by danielhelfand** [comment]
Debugging this further, the TaskRun with a nil Start Time is coming from the PipelineTask `third-hello`. Doing a `kubectl describe` on the TaskRun shows it has a Start Time under Status:

```
kubectl describe tr hello-hello-third-hello-mz2gw-do-extra-hello-prvgv
Name:         hello-hello-third-hello-mz2gw-do-extra-hello-prvgv
Namespace:    default
Labels:       app.kubernetes.io/managed-by=tekton-pipelines
              tekton.dev/conditionCheck=hello-hello-third-hello-mz2gw-do-extra-hello-prvgv
              tekton.dev/pipeline=hello-hello
              tekton.dev/pipelineRun=hello-hello
              tekton.dev/pipelineTask=third-hello
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"hello-hello","namespace":"default"},"spec":{"par...
              pipeline.tekton.dev/release: devel
API Version:  tekton.dev/v1beta1
Kind:         TaskRun
Metadata:
  Creation Timestamp:  2020-04-09T01:02:04Z
  Generation:          1
  Owner References:
    API Version:           tekton.dev/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  PipelineRun
    Name:                  hello-hello
    UID:                   fb55e152-e70b-49db-820a-ce23e6a3f855
  Resource Version:        70733
  Self Link:               /apis/tekton.dev/v1beta1/namespaces/default/taskruns/hello-hello-third-hello-mz2gw-do-extra-hello-prvgv
  UID:                     911c10ec-c2fd-439a-b29c-4bf6f5ac5bea
Spec:
  Params:
    Name:   do-extra-hello
    Value:  true
  Resources:
  Service Account Name:  
  Task Spec:
    Params:
      Name:  do-extra-hello
      Type:  string
    Steps:
      Image:  debian:buster-slim
      Name:   condition-check-do-extra-hello
      Resources:
      Script:  [ "$(inputs.params.do-extra-hello)" = "true" ]
  Timeout:     1h0m0s
Status:
  Completion Time:  2020-04-09T01:02:12Z
  Conditions:
    Last Transition Time:  2020-04-09T01:02:12Z
    Message:               All Steps have completed executing
    Reason:                Succeeded
    Status:                True
    Type:                  Succeeded
  Pod Name:                hello-hello-third-hello-mz2gw-do-extra-hello-prvgv-pod-w8ptk
  Start Time:              2020-04-09T01:02:04Z
  Steps:
    Container:  step-condition-check-do-extra-hello
    Image ID:   docker-pullable://debian@sha256:76c15066d7db315b42dc247b6d439779d2c6466f7dc2a47c2728220e288fc680
    Name:       condition-check-do-extra-hello
    Terminated:
      Container ID:  docker://8201a6bd1dd4295c41d27bd318cf83b4ddc5240387b6246e75d764d8d6293075
      Exit Code:     0
      Finished At:   2020-04-09T01:02:11Z
      Reason:        Completed
      Started At:    2020-04-09T01:02:11Z
Events:
```

I am wondering if this has anything to do with the fact that this command has not been updated to `v1beta1`:

https://github.com/tektoncd/cli/blob/6eae6df140e49e4bee01e65b4967bbf269d10c34/pkg/pipelinerun/description/description.go#L143

**Comment by danielhelfand** [comment]
So I had to make some minor changes for the to the example above to debug this correctly, and I am sharing what I have below:

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  params:
    - name: greeting
      type: string
  steps:
    - name: echo
      image: debian:buster-slim
      command:
        - echo
      args:
        - "Hello World: $(params.greeting)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pause
spec:
  params:
    - name: duration
      type: string
  steps:
    - name: echo
      image: debian:buster-slim
      command:
        - echo
      args:
        - "Sleeping for $(params.duration)"
    - name: sleep
      image: debian:buster-slim
      command:
        - sleep "$(params.duration)"   # mistake included on purpose
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-hello
spec:
  params:
    - name: first-hello
      type: string
      default: wooo
    - name: second-hello
      type: string
      default: yeah
    - name: third-hello
      type: string
      default: heyy
    - name: do-extra-hello
      type: string
      default: "false"
  tasks:
    - name: first-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.first-hello)"

    - name: pause-after-first
      taskRef:
        name: pause
      params:
        - name: duration
          value: "60s"

    - name: second-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.second-hello)"
      runAfter:
        - first-hello

    - name: third-hello
      taskRef:
        name: echo-hello-world
      params:
        - name: greeting
          value: "$(params.third-hello)"
      runAfter:
        - first-hello
      conditions:
        - conditionRef: do-extra-hello
          params:
            - name: do-extra-hello
              value: "$(params.do-extra-hello)"
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: do-extra-hello
spec:
  params:
    - name: do-extra-hello
  check:
    image: debian:buster-slim
    script: '[ "$(params.do-extra-hello)" = "true" ]'
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-hello
spec:
  pipelineRef:
    name: hello-hello
  params:
    - name: first-hello
      value: asdf
    - name: second-hello
      value: zxcv
    - name: do-extra-hello
      value: "true"
```

The problem seems to be that when a condition is part of a TaskRun, the condition name is added to the TaskRun name: `hello-hello-third-hello-4lm88-do-extra-hello-74dhm`. What is coming back from the server for the name of TaskRun is `hello-hello-third-hello-4lm88`. My thought is what is happening here is that TaskRun names aren't being added correctly to the TaskRuns list under Status when a condition is part of the Task. Either the TaskRun name shouldn't have the condition added to it, or the list of TaskRuns available via PipelineRuns should reflect the condition name being added.

So I believe this is actually an issue with pipelines, and I will open an issue there. If the change can be made in pipelines, it should require no changes from `tkn`.
