### ISSUE TITLE
tkn pipeline start - workspaces are always read-only

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/cli#940]
# Expected Behavior

When I run tkn pipeline start, using a workspace which I have not specified to be read-only, I expect the workspace to have read/write access. 

# Actual Behavior
 The PipelineRun fails with errors:
```
cp: can't create 'repo/Dockerfile': Read-only file system
```
 etc. I have also tried specifying `readOnly: false` but this does not work either.

# Steps to Reproduce the Problem

1. Using master of tkn, run `tkn pipeline start` specifying a workspace which should have read/write access and using a task which will need to write to that workspace
2.  Watch it fail
3. Get the logs of the PipelineRun and observe errors such  as the one above.

# Additional Info

**Comment by piyush-garg** [comment]
@Megan-Wright @a-roberts I just had a look over this. Pipeline/Task start command just map your workspace to a PVC or config or secret. It does nothing in terms of the creation of PVC. It just references the existing PVC in the cluster. So this issue is not happening at the CLI level.

Things to note:
1. CLI is still on Pipeline 0.11.x so we yet not support `volumeClaimTemplate` if it works by not doing anything, then I am not aware
2. I have tried https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/workspaces.yaml and it is working perfectly fine with CLI

cc @vdemeester @danielhelfand 

I am moving this issue out of our 0.9.0 milestone as we are about to release and not able to find this bug in the master of tkn.

**Comment by Megan-Wright** [comment]
@piyush-garg Thanks so much for looking into this - I've been using master of CLI so I shouldn't be affected by anything not supported in the last release, and I've been able to run the pipeline successfully without using tkn... that was why I was thinking it must be a CLI issue.

**Comment by Megan-Wright** [comment]
@danielhelfand the resources I'm using are all in this folder: https://github.com/rhd-gitops-example/services/tree/master/tekton-example - sorry for the delayed response, I've ben working the past few days to update and refactor these to make them simpler to use.

**Comment by vdemeester** [comment]
@Megan-Wright Looking at https://github.com/rhd-gitops-example/services/blob/379c24b73b4d23168b64efc3d2ed891ec3736c23/tekton-example/templates/resources.yaml#L36 and [Persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)

> A PersistentVolume can be mounted on a host in any way supported by the resource provider. As shown in the table below, providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities.
> 
> The access modes are:
>
>    ReadWriteOnce -- the volume can be mounted as read-write by a single node
>    ReadOnlyMany -- the volume can be mounted read-only by many nodes
>    ReadWriteMany -- the volume can be mounted as read-write by many nodes

It's very likely that the PV got mounted on a different node than the one the task is currently scheduled (given that it's a workspace, I'm guessing a `git-clone` task). To workaround this, you would need either to use affinity/… to get the tasks to run on the same node *or* have your PVC in `ReadWriteMany`. 

I don't think `tkn` can do anything about it really. If it's an issue, it's most likely a `tektoncd/pipeline` issue. It might also be fixed by `volumeClaim` template support in 0.12.

**Comment by Megan-Wright** [comment]
> @Megan-Wright Looking at https://github.com/rhd-gitops-example/services/blob/379c24b73b4d23168b64efc3d2ed891ec3736c23/tekton-example/templates/resources.yaml#L36 and [Persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
> 
> > A PersistentVolume can be mounted on a host in any way supported by the resource provider. As shown in the table below, providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities.
> > The access modes are:
> > ReadWriteOnce -- the volume can be mounted as read-write by a single node
> > ReadOnlyMany -- the volume can be mounted read-only by many nodes
> > ReadWriteMany -- the volume can be mounted as read-write by many nodes
> 
> It's very likely that the PV got mounted on a different node than the one the task is currently scheduled (given that it's a workspace, I'm guessing a `git-clone` task). To workaround this, you would need either to use affinity/… to get the tasks to run on the same node _or_ have your PVC in `ReadWriteMany`.
> 
> I don't think `tkn` can do anything about it really. If it's an issue, it's most likely a `tektoncd/pipeline` issue. It might also be fixed by `volumeClaim` template support in 0.12.

Hi @vdemeester thanks so much for the suggestions :) I've tried using `ReadWriteMany` for my PVC and this unfortunately hasn't made a difference, I'm still getting the same errors in the PipelineRun...

**Comment by vdemeester** [comment]
> Hi @vdemeester thanks so much for the suggestions :) I've tried using `ReadWriteMany` for my PVC and this unfortunately hasn't made a difference, I'm still getting the same errors in the PipelineRun...

huh :thinking: can you append `--dry-run --output yaml` to your `start` commands to see what is the generated object (in yaml form) that is sent to the API ?

**Comment by Megan-Wright** [comment]
@vdemeester 
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: service-promote-pipeline-run-
  namespace: promote
spec:
  params:
  - name: commitId
    value: v1
  - name: github-config
    value: promote-configmap
  - name: github-secret
    value: promote-secret
  - name: service
    value: service-a
  - name: to
    value: https://github.com/Megan-Wright/gitops-test.git
  pipelineRef:
    name: service-promote-pipeline
  resources:
  - name: docker-image
    resourceRef:
      name: docker-app-image
  - name: git-source
    resourceRef:
      name: git-app-repo
  workspaces:
  - name: repo-space
    secret:
      secretName: promote-secret
status: {}
```
