### ISSUE TITLE
tkn logs gives too many files open.

### ISSUE THREAD

**Issue by ekarlso** [tektoncd/cli#963]
# Version and Operating System

**tkn Version:**
Client version: 0.9.0
Pipeline version: v0.12.0

**Operating System:** 
Ubuntu 20.04

# Expected Behavior
It wouldn't give errors

# Actual Behavior

Lots of fsnotify errors about too many open files.

```
[clone-plumbing : clone] failed to create fsnotify watcher: too many open files
```

# Steps to Reproduce the Problem

Start pipeline for my sake and tkn pipelinerun logs -f <...>

# Additional Info
AKS version 1.15.10

**Comment by danielhelfand** [comment]
Thanks for opening this @ekarlso. If you are comfortable with doing so, could you share your Tasks/Pipeline and how you are starting your PipelineRun (i.e., `kubectl` or `tkn`)?

**Comment by ekarlso** [comment]
pipeline

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tf-check-cfg-drift
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: terraformRepoUrl
    type: string
    description: "URL to the Git repository that has the terraform code."
  - name: terraformRepoSubdirectory
    type: string
    default: infra-terraform
    description: "Name of the directory where we will clone terraform to."
  - name: terraformSubdirectory
    type: string
    description: "Subdirectory containing your .tf files."
  - name: terraformVarFiles
    description: "List of varfiles to use if needed."
    type: string

  - name: plumbingRepoUrl
    type: string

  - name: subscriptionId
    type: string
  - name: tenantId
    type: string

  - name: vaultAddr
    type: string
  - name: vaultRole
    type: string

  tasks:
  - name: clone-plumbing
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.plumbingRepoUrl)
    - name: subdirectory
      value: infra-plumbing
    - name: deleteExisting
      value: "true"

  - name: clone-tf-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.terraformRepoUrl)
    - name: subdirectory
      value: "$(params.terraformRepoSubdirectory)"
    - name: deleteExisting
      value: "true"

  - name: terraform-plan
    workspaces:
    - name: source
      workspace: shared-workspace
    taskRef:
      name: terraform-plan
    runAfter:
      - clone-plumbing
      - clone-tf-repo
    params:
    - name: subdirectory
      value: "$(params.terraformRepoSubdirectory)/$(params.terraformSubdirectory)"
    - name: terraformVarFiles
      value: $(params.terraformVarFiles)

    - name: subscriptionId
      value: "$(params.subscriptionId)"
    - name: tenantId
      value: "$(params.tenantId)"

    - name: vaultAddr
      value: https://vault....
    - name: vaultRole
      value: cicd-prod-tf

  - name: notify-if-drift
    workspaces:
    - name: source
      workspace: shared-workspace
    taskRef:
      name: tf-format-and-notify-slack
    runAfter:
      - terraform-plan
    params:
    - name: webhook-secret
      value: slack-webhook
    - name: msgPath
      value: $(tasks.terraform-plan.results.show)
    conditions:
    - conditionRef: should-exec
      params:
      - name: result
        value: $(tasks.terraform-plan.results.isDrifting)
```

upstream git clone task
tf-plan task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-plan
spec:
  workspaces:
  - name: source
  params:
  - name: subdirectory
    description: "What subdirectory to execute in"
    type: string
  - name: terraformWorkspace
    type: string
    default: "default"
  - name: terraformVarFiles
    type: string
    default: ""

  - name: subscriptionId
    type: string
  - name: tenantId
    type: string

  - name: vaultAddr
    type: string
  - name: vaultRole
    type: string

  - name: utilImage
    type: string
    default: evryace/helm-kubectl-terraform:v3.1.2__v1.13.10__0.12.24
  results:
    - name: plan
    - name: show
    - name: isDrifting
  steps:
    - name: init-and-plan
      image: $(params.utilImage)
      workingDir: $(workspaces.source.path)
      script: |
        export VAULT_ROLE=$(params.vaultRole)
        export VAULT_ADDR=$(params.vaultAddr)
        $(workspaces.source.path)/infra-plumbing/vault/vault-auth-by-msi.sh

        # Terraform part
        export ARM_USE_MSI=true
        export ARM_SUBSCRIPTION_ID="$(params.subscriptionId)"
        export ARM_TENANT_ID="$(params.tenantId)"

        CFG_PATH=$(workspaces.source.path)/$(params.subdirectory)
        cd $CFG_PATH

        terraform init
        [ "$(params.terraformWorkspace)" != "default" ] && terraform workspace select "$(params.terraformWorkspace)"

        set +e
        terraform plan --detailed-exitcode $(params.terraformVarFiles) -out=plan.tfplan

        EXIT_CODE=$?
        set -e

        plan_path=$CFG_PATH/plan.tfplan
        echo -ne "$plan_path" > $(results.plan.path)

        echo -ne $CFG_PATH/plan.show > $(results.show.path)
        terraform show -no-color "$plan_path" > $CFG_PATH/plan.show

        if [ $EXIT_CODE != 0 ]; then
          echo "There was change!"
          echo -ne 1 > $(results.isDrifting.path)
        fi

        echo "done!"
```
